provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  mobilenet:
    lang: dockerfile
    handler: ./mobilenet
    image: alexellis2/mobilenet-flask:0.1
    environment:
      output_image: false
